### ISSUE TITLE
Bug: Can't save some options in Family Plan

### ISSUE THREAD

**Issue by DDisabat** [HTBox/TwoWeeksReady#76]
-Unable to save "Emergency Contacts" in  Family Plan module. Screen recording attached.

-Delay in saving new "Routes and Locations." Time delay in saving can be 10+ seconds or it doesn't save at all. Not consistent. Needs closer look. 

Contact @DDisabat for additional clarity if needed. 

https://user-images.githubusercontent.com/78102622/124667224-f6486400-de63-11eb-97d1-e8704a5307b0.MP4

**Comment by marblekirby** [comment]
Did some triaging on this and found that the family plan API returns `emergecyContacts` (instead of `emergencyContacts`. The vuejs is expecting an array named `emergencyContacts` , because it cannot map `emergecyContacts` to `emergencyContacts` we are getting an error on saving an emergency contact.

Simple typo on the API end.

Fixed on my fork, will add PR for this issue

![image](https://user-images.githubusercontent.com/47943146/126895932-ea5f4de2-fe86-45fc-b987-caf026f06b02.png)

**Comment by marblekirby** [comment]
can we create seperate issue for second problem in this issue? 

-Delay in saving new "Routes and Locations." Time delay in saving can be 10+ seconds or it doesn't save at all. Not consistent. Needs closer look.

**Comment by marblekirby** [comment]
Can you expand on the "Routes and Locations" issue and include some sample data? 
is there specific data that causes it to take long times to save or specific data that causes it not to save?

**Comment by DDisabat** [comment]
Hi all, I am not able to replicate the "Routes and Locations" issue nor do I remember the specific context of the data that I entered. If I am able to replicate this issue or it comes up again, I will reference this post. 

Thanks again so much!
